name: node
type: nodejs:8.9

dependencies:
  nodejs:
    pm2: "^2.2.*"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run npm start"

mounts:
  "/run": "shared:files/run"
  "/templates/hbs": "shared:files/hbs"
  "/site": "shared:files/site"

disk: 512