name: node
type: nodejs:8.9

dependencies:
  nodejs:
    pm2: "^2.2.*"

web:
  commands:
    start: "node ./node_modules/abecms/dist/server/app.js"

mounts:
  "/run": "shared:files/run"
  "/templates/hbs": "shared:files/hbs"
  "/site": "shared:files/site"
  "/data": "shared:files/data"

disk: 512